---
- name: Install prerequisites for SAB
  yum: pkg={{item}} state=present
  with_items:
    - wget
    - git
    - par2cmdline
    - p7zip
    - unrar
    - unzip
    - python-yenc
    - python-feedparser
    - python-configobj
    - python-cheetah
    - python-dbus
    - python-support
    - ftp://ftp.muug.mb.ca/mirror/centos/7.1.1503/os/x86_64/Packages/pyOpenSSL-0.13.1-3.el7.x86_64.rpm

- name: bootstrap SABnzbd install
  copy: src=SABnzbd.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name:    Create dirs 
  command: mkdir -p /apps/data/.sabnzbd

- name:     Clone repo
  command:  git clone https://github.com/sabnzbd/sabnzbd.git /apps/sabnzbd

- name:     Take ownership of apps
  command:  chown -R usenet:usenet /apps

- name: SAB service
  copy: src=sabnzbd.service
        dest=/etc/systemd/system/
        owner=root group=root mode=0644

- name:     enable SAB service
  command:  systemctl enable sabnzbd.service

