---
- hosts: all
  sudo: true
  vars:
   # created with:
   # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
   password: $1$SomeSalt$UqddPX3r4kH3UL5jq5/ZI.

  tasks:
    # Create user
    - name: test basic user account creation
      user: name=usenet comment=UsenetUser group=admins password= {{ password }}
	
	