---
- hosts: proxy
  gather_facts: no
  sudo: true

  pre_tasks:
    - shell: echo 'hello'
    
  roles:
    - common
    - openssl
    - nginx
    - firewall

  post_tasks:
    - name: Reboot system
      raw: /sbin/shutdown -r 1
      changed_when: True
  
    # If we need to use this server again after restart, use below...
    # - name: Wait for system to complete reboot (5 min max / 90 sec delay)
    #   wait_for: host=192.168.125.6 port=22 timeout=300 delay=90 state=started
    #   delegate_to: 127.0.0.1
    #   ignore_errors: yes